{
  "comments": [
    {
      "key": {
        "uuid": "5ad0253b_3bf3a475",
        "filename": "ci-scripts/infra-cleanup/ovb-tenant-cleanup.sh",
        "patchSetId": 8
      },
      "lineNbr": 177,
      "author": {
        "id": 517
      },
      "writtenOn": "2019-01-30T09:20:15Z",
      "side": 1,
      "message": "Wihtout set -e will \"run\" function propagate exit ?",
      "revId": "096f88232f3029f8b2ac30efa3443408ff045a49",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5ad0253b_7bf91c4d",
        "filename": "ci-scripts/infra-cleanup/ovb-tenant-cleanup.sh",
        "patchSetId": 8
      },
      "lineNbr": 177,
      "author": {
        "id": 371
      },
      "writtenOn": "2019-01-30T09:25:11Z",
      "side": 1,
      "message": "set -e is setup near the start of the script so it will always be set. To answer your question: bash functions that return non zero act identically as other commands, so with -e mode it will trigger an exit too.\n\nIt is a little bit incorrect to say propage-exit, as they only return an error code. The decision to exit is made by bash, noth the function itself.\n\nAnd asyouy know \"cmd-with-error || true\" does not trigger any exit.",
      "parentUuid": "5ad0253b_3bf3a475",
      "revId": "096f88232f3029f8b2ac30efa3443408ff045a49",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5ad0253b_db8950cc",
        "filename": "ci-scripts/infra-cleanup/ovb-tenant-cleanup.sh",
        "patchSetId": 8
      },
      "lineNbr": 177,
      "author": {
        "id": 517
      },
      "writtenOn": "2019-01-30T09:26:37Z",
      "side": 1,
      "message": "ack",
      "parentUuid": "5ad0253b_7bf91c4d",
      "revId": "096f88232f3029f8b2ac30efa3443408ff045a49",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}