{
  "comments": [
    {
      "key": {
        "uuid": "d758d972_b8355961",
        "filename": "ci-scripts/dlrnapi_promoter/config_environments/rdo/defaults.yaml",
        "patchSetId": 58
      },
      "lineNbr": 14,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-09-09T08:21:20Z",
      "side": 1,
      "message": "maybe try without the ~ make it explicit? try {{ ansible_user_dir }}/web/ ... ?",
      "revId": "cb35dcffc9ccac5326d46f28b6c390c90d52dcbd",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "410899c7_9f73337e",
        "filename": "ci-scripts/dlrnapi_promoter/config_environments/rdo/defaults.yaml",
        "patchSetId": 58
      },
      "lineNbr": 14,
      "author": {
        "id": 670
      },
      "writtenOn": "2020-09-09T09:51:06Z",
      "side": 1,
      "message": "this is rdo/defualt.yaml we need to check for staging/default.yaml",
      "parentUuid": "d758d972_b8355961",
      "revId": "cb35dcffc9ccac5326d46f28b6c390c90d52dcbd",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "8e1f7daa_42e2c8c7",
        "filename": "ci-scripts/dlrnapi_promoter/config_environments/rdo/defaults.yaml",
        "patchSetId": 58
      },
      "lineNbr": 14,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-09-09T10:59:34Z",
      "side": 1,
      "message": "the problem is the parent directories\n\nlocally when i create ~/web/promoter_logs/ then re-run it gets passed the logfile issue.",
      "parentUuid": "410899c7_9f73337e",
      "revId": "cb35dcffc9ccac5326d46f28b6c390c90d52dcbd",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "8acd715c_7a980692",
        "filename": "ci-scripts/dlrnapi_promoter/config_environments/staging/defaults.yaml",
        "patchSetId": 58
      },
      "lineNbr": 36,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-09-09T08:21:20Z",
      "side": 1,
      "message": "the py36 tests can\u0027t find that/the error points to it like:\n\n        * https://logserver.rdoproject.org/81/28081/58/check/tox-py36-ci-config/d45aa66/tox/reports.html\n        * ci-scripts/dlrnapi_promoter/test_dlrn_integration.py::test_dlrn_server[dlrn_legacyconf_integration]::setup\n        * E           config_legacy.ConfigError\n        * ERROR    promoter:common.py:164 Invalid Log file: /home/zuul/web/promoter_logs/centos8_master.log\n          ERROR    promoter:config_legacy.py:208 Error in configuration file staging/CentOS-8/master.ini",
      "range": {
        "startLine": 36,
        "startChar": 9,
        "endLine": 36,
        "endChar": 28
      },
      "revId": "cb35dcffc9ccac5326d46f28b6c390c90d52dcbd",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}