{
  "comments": [
    {
      "key": {
        "uuid": "98a87677_1a537ba8",
        "filename": "ci-scripts/dlrnapi_promoter/dlrnapi_promoter.py",
        "patchSetId": 12
      },
      "lineNbr": 55,
      "author": {
        "id": 371
      },
      "writtenOn": "2020-02-17T16:10:25Z",
      "side": 1,
      "message": "I do not find acceptable to return success code when exception occured. See POSIX specs ;)",
      "range": {
        "startLine": 54,
        "startChar": 0,
        "endLine": 55,
        "endChar": 31
      },
      "revId": "f83d27ff7dda822983273c57a72107fac729d946",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}